import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return <>
        <Head>
            <title>Database users</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <div className="todo-container">
                <Link href="/users" className="custom-link">Перейти к списку пользователей</Link>
            </div>
        </main>
    </>
}